server:
  port: 8002
spring:
  application:
    name: spring-boot-grpc-client

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
grpc:
  client:
    spring-boot-grpc-server:
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext